update rspec syntax to be 3.0-compatible
In 2.x you could say expect(asdlfkd).to be_true even if the argument to
expect was true.  In 3.0 you get:

  1) BigintPk::Generators::InstallGenerator creates a bigint_pk initializer
     Failure/Error: expect( File.exists? "#{RailsDir}/config/initializers/bigint_pk.rb").to be_true
     NoMethodError:
       undefined method `true?' for true:TrueClass
     # ./spec/integration/generator_spec.rb:13:in `block (2 levels) in <top (required)>'